---
title: "Causal_project"
output: html_document
date: '2022-11-15'
---
## Install packages & library
```{r}
#install.packages("remotes")
#remotes::install_github("ygeunkim/propensityml")
#install.packages("dplyr")
#install.packages("sas7bdat")

library(propensityml)
library(dplyr)
library(sas7bdat)

```
# 1. Chemical Dataset
## 1-1. Data reading
```{r}
df<-read.table('/Users/kyungseonlee/Desktop/causal/poisox.txt')
colnames(df)=c('age','sex','prior','poisox','subseq','mortal')
df%>% head()

#df0 has integer values.
df0=df[c(1,2,4,6)]
df0 %>% head()

#df1 has factor values.
df1=df0
df1[2:4]=lapply(df1[2:4],factor)
df1 %>% head()
```
## 1-2. Propensity score estimation- logistic regression, random Forest, CART
```{r}
# a. propensity score estimation-logistic regression
log_reg_ps=glm(poisox~ age+sex, family = "binomial", data=df)
logit_e_hat=predict(log_reg_ps)
print(logit_e_hat %>% head())

#exp(logit_e_hat)
e_hat=exp(logit_e_hat)/(1+exp(logit_e_hat))
print(e_hat %>% head())
```

```{r}
# a-1. propensity score estimation-logistic regression by package

log_reg_ps2=ps_glm(poisox~ age+sex, data=df)
e_hat2=estimate_ps(log_reg_ps2)
e_hat2 %>% head()

print(sum(e_hat!=e_hat2))

```

```{r}
# b.  propensity score estimation- Random Forest
#install.packages("randomForest")
library(randomForest)
rf=randomForest(poisox~ age+sex, data=df)
e_hat=predict(rf)
print(e_hat %>% head())

```

```{r}
# b.  propensity score estimation- Random Forest by package
```

```{r}
#c. propensity score estimation- CART
#install.packages("rpart")
library(rpart)
cart=rpart(poisox~ age+sex, data=df0 ,method='poisson')
summary(cart)

df0_c=df0
cart_ps=predict(cart)
df0_c["propensity score"]=cart_ps
df0_c %>% head()

df1_c=df1
cart=rpart(poisox~ age+sex, data=df1 ,method='class')
summary(cart)

cart_ps=predict(cart)
df1["propensity score2"]=cart_ps
df1 %>% head()

```


```{r}
#c. propensity score estimation- CART by package

cart2=ps_cart(poisox ~ age + sex, data = df1)
cart_ps2=estimate_ps(cart2)
df1["propensity score"]=cart_ps2
df1 %>% head()

```




# 2. Korea National Health and Nutrition Examination Survey Dataset
## 2-1. Data reading
```{r}

raw_data <- read.sas7bdat("/Users/kyungseonlee/snu-causal/main/input/rawdata/HN20_ALL.sas7bdat")
dim(raw_data) %>% head()
raw_data %>% head(1)

```

# 2-2. Data preprocessing
```{r}
column=c('BD1','DC2_dg','sex','age','DK8_dg','DK9_dg','DK4_dg')
column2=c('BD1','DC2_dg','DK8_dg','DK9_dg','DK4_dg')

df=raw_data[,column]
df %>% head(7)

df <- df[!(df$BD1 == 8 | df$BD1 ==9 ), ]
df <- df[!(df$DC2_dg == 8 | df$DC2_dg ==9 ), ]
df <- df[!(df$DK8_dg == 8 | df$DK8_dg ==9 ), ]
df <- df[!(df$DK9_dg == 8 | df$DK9_dg ==9 ), ]
df <- df[!(df$DK4_dg == 8 | df$DK4_dg ==9 ), ]

df %>% head(7)
```


```{r}
df$BD1<-df$BD1-1
df$sex<-df$sex-1

table(df$BD1)
```
```{r}
linear_model=lm(BD1~., data=df)
summary(linear_model)

```

### LaLonde dataset
```{r}

haven::read_data("http://www.nber.org/~rdehejia/data/nsw_dw.dta")

lalonde::nsw_dw

data(LaLonde)

print(data)

y <- LaLonde$outcome

trt <- LaLonde$treat

x.varnames <- c("age", "educ", "black", "hisp", "white",
                "marr", "nodegr", "log.re75", "u75")

# covariates
data.x <- LaLonde[, x.varnames]



# construct design matrix (with no intercept)
x <- model.matrix(~ -1 + ., data = data.x)

const.propens <- function(x, trt)
{
    mean.trt <- mean(trt == "Trt")
    rep(mean.trt, length(trt))
}

subgrp_fit_w <- fit.subgroup(x = x, y = y, trt = trt,
    loss = "logistic_loss_lasso",
    propensity.func = const.propens,
    cutpoint = 0,
    type.measure = "auc",
    nfolds = 10)

summary(subgrp_fit_w)
```

